name: 'Create Pull Request Action'
description: 'A GitHub Action to create a pull request using Octokit'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  repo:
    description: 'Repository name in the form owner/repo'
    required: true
  base:
    description: 'The base branch to create the pull request against'
    required: true
  head:
    description: 'The branch that contains the changes'
    required: true
  title:
    description: 'Title of the pull request'
    required: true
  body:
    description: 'Body of the pull request'
    required: false
outputs:
  pull_request_url:
    description: 'The URL of the created pull request'
runs:
  using: 'node20'
  main: 'index.js'
